// <auto-generated />
using System;
using EntryProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntryProject.Migrations
{
    [DbContext(typeof(TriageDbContext))]
    [Migration("20260721095725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntryProject.Data.RoleStat", b =>
                {
                    b.Property<double>("AvgEarlyAdoptionScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_early_adoption_score");

                    b.Property<double>("AvgExperimentationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_experimentation_score");

                    b.Property<double>("AvgIterationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_iteration_score");

                    b.Property<double>("AvgOutputVerificationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_output_verification_score");

                    b.Property<double>("AvgSavedWorkflowsScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_saved_workflows_score");

                    b.Property<double>("AvgSharingScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_sharing_score");

                    b.Property<double>("AvgTotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_total_score");

                    b.Property<long>("ResponseCount")
                        .HasColumnType("bigint")
                        .HasColumnName("response_count");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("EntryProject.Data.TriageResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EarlyAdoptionScore")
                        .HasColumnType("integer")
                        .HasColumnName("early_adoption_score");

                    b.Property<int>("ExperimentationScore")
                        .HasColumnType("integer")
                        .HasColumnName("experimentation_score");

                    b.Property<int>("IterationScore")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_score");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<bool>("Management")
                        .HasColumnType("boolean")
                        .HasColumnName("management");

                    b.Property<int>("OutputVerificationScore")
                        .HasColumnType("integer")
                        .HasColumnName("output_verification_score");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("SavedWorkflowsScore")
                        .HasColumnType("integer")
                        .HasColumnName("saved_workflows_score");

                    b.Property<int>("SharingScore")
                        .HasColumnType("integer")
                        .HasColumnName("sharing_score");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.ToTable("triage_results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
