CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260721095725_InitialCreate') THEN
    CREATE TABLE triage_results (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role integer NOT NULL,
        early_adoption_score integer NOT NULL,
        experimentation_score integer NOT NULL,
        iteration_score integer NOT NULL,
        output_verification_score integer NOT NULL,
        saved_workflows_score integer NOT NULL,
        sharing_score integer NOT NULL,
        total_score integer NOT NULL,
        level integer NOT NULL,
        management boolean NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_triage_results" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260721095725_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260721095725_InitialCreate', '9.0.8');
    END IF;
END $EF$;
COMMIT;

